// Ten-Yen deck. Drafted with Gemini, then read and pruned by hand (drops: odd, unclear or judgy lines).
export const DECK: readonly string[] = [
  "Have you ever ordered food just to avoid washing dishes?",
  "Do you judge people who eat Momos with ketchup?",
  "Is Chai better than Coffee any day of the week?",
  "Have you ever eaten Maggi for dinner three days in a row?",
  "Do you put Maggi masala on things that aren't Maggi?",
  "Have you been part of a Goa plan that actually succeeded?",
  "Do you pack way more clothes than you actually wear on trips?",
  "Have you ever stolen toiletries from a hotel room?",
  "Do you scroll on your phone while your food gets cold?",
  "Have you ever stalked an ex's new partner on Instagram?",
  "Do you have over 1,000 unread emails or WhatsApp texts?",
  "Have you ever ignored a call and texted 'I was sleeping'?",
  "Do you watch reels on mute with captions?",
  "Have you ever sent a text to the wrong group and panicked?",
  "Do you practice faces in the mirror before taking a selfie?",
  "Have you ever lied on your resume about knowing Excel?",
  "Have you ever muted a Zoom call to gossip about the speaker?",
  "Did you ever give a proxy attendance for a friend who was asleep?",
  "Have you ever cried because of a work email?",
  "Do you check your bank balance before making a UPI payment?",
  "Have you ever taken a 'sick leave' when you were completely fine?",
  "Have you ever worn the same t-shirt two days in a row?",
  "Do you sing concert-style when you are alone in the shower?",
  "Have you ever pretended to recognize someone you had no clue about?",
  "Do you still count on your fingers for basic math?",
  "Have you ever rehearsed an argument in the shower and won?",
  "Do you wave back at people who were actually waving at someone else?",
  "Have you ever kept a plastic bag inside another plastic bag?",
  "Have you ever lied to your parents about your location?",
  "Do you have a 'good clothes' pile that is distinct from 'home clothes'?",
  "Have you ever saved a gift to re-gift it to someone else?",
  "Do you struggle to say 'No' to relatives asking about your life?",
  "Have you ever cried while watching a K-drama or Bollywood movie?",
  "Do you skip the intro of a show even if you love the song?",
  "Have you ever tried to copy a Bollywood dance step in your room?",
  "Do you think Pani Puri is the ultimate Indian street food?",
  "Have you ever eaten leftovers straight out of the fridge at 2 AM?",
  "Do you negotiate with auto drivers even when you know they'll say no?",
  "Have you ever bought something just because it was on sale?",
  "Do you close 50 open tabs on your browser only once a month?",
  "Have you ever pretended to be on a call to avoid talking to someone?",
  "Do you still use your ex's Netflix or Prime account?",
  "Have you ever stalked your school crush on LinkedIn?",
  "Do you always check reviews before buying a 100-rupee item?",
  "Have you ever worn nice pajamas on a video call but wore shorts below?",
  "Do you set ten alarms five minutes apart to wake up?",
  "Have you ever sniffed your clothes to check if they are clean?",
  "Do you get anxious when the delivery guy calls for directions?",
  "Have you ever lied about your age to get a discount?",
  "Do you calculate how many hours of sleep you'll get before sleeping?",
  "Have you ever put your phone on airplane mode just for peace of mind?"
];
